export enum MirageObjectType {
  USER = "USER",
  ENTITY = "ENTITY",
  SHOS = "SHOS",
  DYNAMIC_TAG = "DYNAMIC_TAG",
  END_SYSTEM = "END_SYSTEM",
  PROFILE = "PROFILE",
  DISTRIBUTION_GROUP = "DISTRIBUTION_GROUP",
  PARAMETER = "PARAMETER",
  SYSTEM = "SYSTEM",
}
