import { makeStyles } from '@/lib/makeStyles';

export const styles = makeStyles((t) => ({
    container: `${t.colors.border} rounded-lg bg-background ${t.colors.transition} border`,
    containerExpanded: t.colors.ring,
    mainRow: `w-full grid grid-cols-12 gap-4 px-4 py-3 items-center text-right ${t.colors.hover} transition-colors rounded-lg`,
    timestampCol: 'col-span-2 flex items-center gap-2',
    chevron: `${t.colors.textSecondary} shrink-0`,
    chevronIcon: 'h-4 w-4',
    dateText: `${t.typography.sm} ${t.typography.medium} ${t.colors.textPrimary} truncate`,
    timeText: `${t.typography.xs} ${t.colors.textSecondary} ${t.typography.mono}`,
    usernameCol: 'col-span-2 min-w-0',
    username: `${t.typography.sm} ${t.colors.textPrimary} truncate ${t.typography.semibold}`,
    userId: `${t.typography.xs} ${t.colors.textSecondary} ${t.typography.mono} truncate`,
    actionCol: 'col-span-3 min-w-0 text-right',
    action: `${t.typography.sm} ${t.typography.medium} ${t.colors.textBrand} truncate`,
    targetCol: 'col-span-3 min-w-0 text-right',
    targetName: `${t.typography.sm} ${t.colors.textPrimary} truncate ${t.typography.semibold}`,
    targetInfo: 'flex items-center justify-start gap-1.5 mt-1 flex-wrap',
    targetId: `${t.typography.xs} ${t.colors.textSecondary} ${t.typography.mono} truncate`,
    resourceCol: 'col-span-2 min-w-0 text-right',
    resourceType: `${t.typography.sm} ${t.colors.textPrimary} truncate ${t.typography.semibold}`,
    resourceId: `${t.typography.xs} ${t.colors.textSecondary} ${t.typography.mono} truncate`,
    expandedDetails: 'px-4 pb-4 pt-2 border-t space-y-4 animate-fade-in',
    detailsGrid: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4',
    detailsSection: 'space-y-3',
    detailsHeader: `${t.typography.xs} ${t.typography.semibold} ${t.colors.textSecondary} uppercase tracking-wider`,
    detailsList: `space-y-2 ${t.typography.sm}`,
    detailsItem: 'flex items-start gap-2',
    detailsIcon: `w-4 h-4 ${t.colors.textSecondary} mt-0.5`,
    detailsLabel: t.colors.textSecondary,
    detailsValue: `${t.typography.mono} ${t.typography.xs} ${t.colors.textPrimary} break-all`,
    targetList: `space-y-1 ${t.typography.sm}`,
    userAgentText: `${t.typography.xs} ${t.colors.textSecondary} break-words`,
    stateChangesGrid: 'grid grid-cols-1 md:grid-cols-2 gap-4',
    stateSection: 'space-y-2',
    jsonPre: `font-sans ${t.typography.xs} ${t.colors.bgSecondary} p-3 rounded-md overflow-auto max-h-32 scrollbar-thin`,
    contextSection: 'space-y-2',
    loadingContainer: 'flex justify-center py-6',
    loadingIcon: 'w-6 h-6 animate-spin text-muted-foreground',
    stateChangesSection: 'mt-4',
    stateDiffWrapper: 'mt-2 border rounded-md p-4 bg-white/50',
}));
