import { makeStyles } from '@/lib/makeStyles';

export const styles = makeStyles({
    container: 'border rounded-lg bg-card transition-all duration-200',
    containerExpanded: 'ring-1 ring-primary/20',
    containerFailure: 'border-failure/30 bg-failure/5',
    mainRow: 'w-full grid grid-cols-12 gap-4 px-4 py-3 items-center text-right hover:bg-table-row-hover transition-colors rounded-lg',
    timestampCol: 'col-span-2 flex items-center gap-2',
    chevron: 'text-muted-foreground shrink-0',
    dateText: 'text-sm font-medium text-foreground truncate',
    timeText: 'text-xs text-muted-foreground font-mono',
    actorTypeCol: 'col-span-2',
    usernameCol: 'col-span-2 min-w-0',
    username: 'text-sm text-foreground truncate',
    userId: 'text-xs text-muted-foreground font-mono truncate',
    actionCol: 'col-span-2 min-w-0',
    action: 'text-sm font-medium text-primary truncate',
    resourceCol: 'col-span-2 min-w-0',
    resourceType: 'text-sm text-foreground truncate',
    resourceId: 'text-xs text-muted-foreground font-mono truncate',
    targetTypeCol: 'col-span-2',
    expandedDetails: 'px-4 pb-4 pt-2 border-t space-y-4 animate-fade-in',
    outcomeIndicator: 'flex items-center gap-2',
    outcomeSuccess: 'inline-flex items-center gap-1.5 text-sm text-success',
    outcomeFailure: 'inline-flex items-center gap-1.5 text-sm text-failure',
    detailsGrid: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4',
    detailsSection: 'space-y-3',
    detailsHeader: 'text-xs font-semibold text-muted-foreground uppercase tracking-wider',
    detailsList: 'space-y-2 text-sm',
    detailsItem: 'flex items-start gap-2',
    detailsIcon: 'w-4 h-4 text-muted-foreground mt-0.5',
    detailsLabel: 'text-muted-foreground',
    detailsValue: 'font-mono text-xs text-foreground break-all',
    targetList: 'space-y-1 text-sm',
    userAgentText: 'text-xs text-muted-foreground break-words',
    stateChangesGrid: 'grid grid-cols-1 md:grid-cols-2 gap-4',
    stateSection: 'space-y-2',
    jsonPre: 'text-xs bg-muted p-3 rounded-md overflow-auto max-h-32 scrollbar-thin',
    contextSection: 'space-y-2',
});
