import { makeStyles } from '@/lib/makeStyles';

export const styles = makeStyles({
    container: 'border rounded-lg bg-card transition-all duration-200',
    containerExpanded: 'ring-1 ring-primary/20',
    mainRow: 'w-full grid grid-cols-12 gap-4 px-4 py-3 items-center text-right hover:bg-table-row-hover transition-colors rounded-lg',
    timestampCol: 'col-span-2 flex items-center gap-2',
    chevron: 'text-muted-foreground shrink-0',
    chevronIcon: 'h-4 w-4',
    dateText: 'text-sm font-medium text-foreground truncate',
    timeText: 'text-xs text-muted-foreground font-mono',
    usernameCol: 'col-span-2 min-w-0',
    username: 'text-sm text-foreground truncate font-medium',
    userId: 'text-xs text-muted-foreground font-mono truncate',
    actionCol: 'col-span-3 min-w-0 text-right',
    action: 'text-sm font-medium text-primary truncate',
    targetCol: 'col-span-3 min-w-0 text-right',
    targetName: 'text-sm text-foreground truncate font-medium',
    targetInfo: 'flex items-center justify-start gap-1.5 mt-1 flex-wrap',
    targetId: 'text-xs text-muted-foreground font-mono truncate',
    resourceCol: 'col-span-2 min-w-0 text-right',
    resourceType: 'text-sm text-foreground truncate font-medium',
    resourceId: 'text-xs text-muted-foreground font-mono truncate',
    expandedDetails: 'px-4 pb-4 pt-2 border-t space-y-4 animate-fade-in',
    detailsGrid: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4',
    detailsSection: 'space-y-3',
    detailsHeader: 'text-xs font-semibold text-muted-foreground uppercase tracking-wider',
    detailsList: 'space-y-2 text-sm',
    detailsItem: 'flex items-start gap-2',
    detailsIcon: 'w-4 h-4 text-muted-foreground mt-0.5',
    detailsLabel: 'text-muted-foreground',
    detailsValue: 'font-mono text-xs text-foreground break-all',
    targetList: 'space-y-1 text-sm',
    userAgentText: 'text-xs text-muted-foreground break-words',
    stateChangesGrid: 'grid grid-cols-1 md:grid-cols-2 gap-4',
    stateSection: 'space-y-2',
    jsonPre: 'text-xs bg-muted p-3 rounded-md overflow-auto max-h-32 scrollbar-thin',
    contextSection: 'space-y-2',
});
